default:
    image: python:3.8

cache:
  paths:
    - .cache/pip
    - venv/

stages:
    - build
    - test

unittests:
    stage: test
    before_script:
        - echo "Running unit tests."
        - mkdir logs
        - mkdir logs/test-logs
        - apt update
        - apt-get --yes install graphviz
        - pip install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - pip install -r requirements/main.txt
        - pwd
    script:
        - "cd tests/ && python3 -m unittest"
    after_script:
        - echo "Finished running unit tests."
